name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        reuqired: true
        description: Greet message
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
